baseURL = "https://optimum.ba"
languageCode = "en-us"
title = "Optimum"
enableRobotsTXT = true
disableKinds = ["taxonomy", "term"]

[params]
  description = "Full-stack software development agency specializing in the PETAL stack — Phoenix, Elixir, TailwindCSS, Alpine.js, LiveView."
  email = "projects@optimum.ba"
  twitter = "https://twitter.com/optimumBA"
  github = "https://github.com/optimumBA"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3
    ordered = false

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Services"
    url = "/#services"
    weight = 2
  [[menu.main]]
    name = "Blog"
    url = "/#blog"
    weight = 3
  [[menu.main]]
    name = "Portfolio"
    url = "/portfolio/"
    weight = 4
